### ISSUE TITLE
URGENT: proposals are editable after phase closes

### ISSUE THREAD

**Issue by Nebules** [ecsion/eSeaGrant-Client-Bug-Tracker#1053]
We had a deadline of 5p today, and I was editing a test proposal to confirm that PIs could not alter their proposals after the deadline. But while a notice appeared that "Full Proposal Phase was closed", I was able to continue making edits to my test proposal, as you'll see indicated in it's title:

https://eseagrant.mit.edu/index.php?module=RFPProposal&view=Detail&record=118526&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

**Comment by ecsion** [comment]
Ben, When you are logged in as Administrator, the due date does not apply. When you took the screen grab, you were logged in as administrator and so it allows you to update the proposal. If you login in as the PI, it does not allow you to update the proposal.

I am closing this issue. If you feel there is still some other issue, please reopen it.

**Comment by Nebules** [comment]
how do I re-open it? you’ve made an incorrect assumption.

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jun 1, 2020, at 5:53 PM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



Ben, When you are logged in as Administrator, the due date does not apply. When you took the screen grab, you were logged in as administrator and so it allows you to update the proposal. If you login in as the PI, it does not allow you to update the proposal.

I am closing this issue. If you feel there is still some other issue, please reopen it.

**Comment by ecsion** [comment]
fixed, please check

**Comment by Nebules** [comment]
I tried it again and the problem persists. See proposal title:

https://eseagrant.mit.edu/index.php?module=RFPProposal&view=Detail&record=118526&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

b

------

Web Developer, MIT Sea Grant
Massachusetts Institute of Technology
77 Massachusetts Ave NW98-165
Cambridge, MA 02139
phone: 617.252.1675
e-mail: bbray@mit.edu<mailto:bbray@mit.edu>
www: https://seagrant.mit.edu<http://seagrant.mit.edu/>



On Jun 2, 2020, at 11:21 AM, Ecsion <notifications@github.com<mailto:notifications@github.com>> wrote:



fixed, please check
