### ISSUE TITLE
RISG:: Error in Fellowship"View Listing" Dashboard

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1108]
at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=showProposals&record=117385&phaseid=117387&tab_label=RmVsbG93c2hpcCBBcHBsaWNhdGlvbg==&showList=
you see that one entry (see screenshot below) shows that Graduate Transcripts are uploaded (dot is GREEN).
![fellowship_listing_error](https://user-images.githubusercontent.com/18398763/107550855-89c08600-6b9f-11eb-9a33-b1b745e5118b.jpg)
Yet at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=117950&mode=showMultiQuestionStem&QuestionId=117393&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBHcmFkdWF0ZSBUcmFuc2NyaXB0cw==&showList=&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBHcmFkdWF0ZSBUcmFuc2NyaXB0cw== 
You see that the transcripts are indeed not uploaded.
This should be corrected so that the dot in the dashboard is RED when the transcripts are not uploaded. Thank you.

**Comment by alandesbonnet** [comment]
Also, at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=117654&mode=showMultiQuestionStem&QuestionId=117390&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBDdXJyaWN1bHVtIFZpdGFlIC8gUmVzdW1l&showList=&tab_label=S25hdXNzIEZlbGxvd3NoaXAgLSBDdXJyaWN1bHVtIFZpdGFlIC8gUmVzdW1l
You see that there is NO CV/Resume uploaded, Yet the screenshot below (in blue) show that it is (green dot, in error).
![fellowship_listing_error2](https://user-images.githubusercontent.com/18398763/107554573-22590500-6ba4-11eb-8fe3-b1fef331c899.jpg)
This too needs to be corrected. Thank you.

**Comment by ecsion** [comment]
Alan, This is a new dashboard and appears like there are some logic issue. We will troubleshoot and fix.

**Comment by ecsion** [comment]
This is fixed, please check. We are also adding form popup on click of dot so you can see the user's response right there. This is still in progress and should be done by end of week.

**Comment by alandesbonnet** [comment]
Not fixed that I can see. The same errors are still showing up. I emptied cache etc just to be sure but the errors are still showing.

Alan Desbonnet
Interim Director
