### ISSUE TITLE
CASG: Key Personnel Not Showing Up on RFP

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#240]
Hi,

I've selected "Key Personnel" in the "Mandatory for Sea Grant" form, but it's not showing up in the RFP (I've created a separate account as a PI to test the system):

![screen shot 2016-06-06 at 1 30 38 pm](https://cloud.githubusercontent.com/assets/17860279/15836735/0cc4a3dc-2beb-11e6-8d01-0eab9c90a782.png)

Also, the budget sheet shows "MIT Sea Grant College..." on the upper tab. Can we change that so it's not confusing to our PIs? 

![screen shot 2016-06-06 at 1 30 02 pm](https://cloud.githubusercontent.com/assets/17860279/15836755/24fd4ecc-2beb-11e6-92c6-b032650e63db.png)

Thanks,

Miho

**Comment by mumezawa** [comment]
Hi, 

I see that Key Personnel and Investigators are now up. They seem redundant to me but since both are mandatory forms, I can't get rid of Key Personnel. I'm fine with using Investigators (and they can upload a CV), then we can get rid of the Key Personnel and CVs forms (I already deleted the CV form). Please let me know if that makes sense.

![screen shot 2016-06-09 at 9 49 28 am](https://cloud.githubusercontent.com/assets/17860279/15938342/a2d4e182-2e27-11e6-8738-7f7943de0b13.png)

Thanks,

Miho

**Comment by mumezawa** [comment]
Hi, 

Can we please get rid of the Key Personnel form? It seems redundant with Investigator. I've already gotten rid of the CV form since PIs can upload their CVs through the Investigator form. Also, please delete "You may use the SG resume template, or your own format." in the instructions? I'm not sure what the SG resume template is. 

![screen shot 2016-06-09 at 9 49 28 am](https://cloud.githubusercontent.com/assets/17860279/15939199/8ed6da4c-2e2b-11e6-99a3-053b0bf7b04a.png)


Thanks, 
Miho

**Comment by ecsion** [comment]
fixed.

**Comment by mumezawa** [comment]
Hello,

Both the "Key Personnel" and ³Investigator² are still showing up on the 2017
Special Focus Awards RFP.

Can you please  get rid of the Key Personnel form? It seems redundant with
Investigator. I've already gotten rid of the CV form since PIs can upload
their CVs through the Investigator form.
Since both of these forms are mandatory, I can¹t uncheck the boxes as an
admin. 
Also, please delete "You may use the SG resume template, or your own
format." in the instructions. I'm not sure what the SG resume template is.


Thanks,
Miho


Miho Umezawa | Research & Fellowship Coordinator
California Sea Grant
University of California, San Diego
Scripps Institution of Oceanography
9500 Gilman Dr., 0232
La Jolla, CA 92093-0232
(858) 534-1160
mumezawa@ucsd.edu
https://caseagrant.ucsd.edu


From:  ecsion <notifications@github.com>
Reply-To:  ecsion/eSeaGrant-Client-Bug-Tracker
<reply+011086b7878b662d2ee3be2f8932f1efc0c87ff3949e900892cf00000001137197509
2a169ce09769c8d@reply.github.com>
Date:  Thursday, June 9, 2016 at 1:45 PM
To:  ecsion/eSeaGrant-Client-Bug-Tracker
<eSeaGrant-Client-Bug-Tracker@noreply.github.com>
Cc:  Miho Umezawa <mumezawa@ucsd.edu>, Author <author@noreply.github.com>
Subject:  Re: [ecsion/eSeaGrant-Client-Bug-Tracker] CASG: Key Personnel Not
Showing Up on RFP (#240)


fixed. 


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/240#issuecomm
ent-225020743> , or mute the thread
<https://github.com/notifications/unsubscribe/ARCGt7_He41jOv6IBsMhI8EKHv9TrJ
Rnks5qKHtQgaJpZM4IvSYH> .

**Comment by mumezawa** [comment]
Under "Investigator" instructions,  please delete "You may use the SG resume template, or your own
format." in the instructions. I'm not sure what the SG resume template is.
Please also delete "DO NOT include page numbers, headers, or footers". 

Under "Key Personnel", please delete the current instructions, "Please include all project PIs, Co-PIs, and Associate PIs." and replace it with "Please include all key personnel who are NOT listed as investigators (ex. Post doc student).  NOTE: CVs cannot be uploaded for key personnel.". 

![screen shot 2016-06-10 at 3 52 58 pm](https://cloud.githubusercontent.com/assets/17860279/15980847/73ebd6e4-2f23-11e6-90e5-a41f27b45861.png)

Thank you.
