### ISSUE TITLE
CASG: URGENT Special Focus Award - Changing Titles 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#287]
Hi,

Is there a way to change the proposal title once one is started? 

In particular, I'm hoping to change Colgan's proposal to "Development of a Prototype Community Risk Assessment Process for Shoreline Erosion Response Using Southern Monterey Bay" from "Incorporating Explicit Measurement of Risk and Uncertainty in Planning for Responses to Beach Erosion: A Case Study of Southern Monterey Bay". 

http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=16334&mode=showInstructions&tab_label=Instructions

We're moving forward with peer and science reviewers so if you could do this asap, it would eliminate possible confusion by the reviewers and be greatly appreciated. 

Thanks,

Miho

**Comment by ecsion** [comment]
fixed.

**Comment by mumezawa** [comment]
It's still showing up as the old title... 

http://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=16334&mode=showInstructions&tab_label=Instructions

 
![screen shot 2016-07-29 at 10 51 32 am](https://cloud.githubusercontent.com/assets/17860279/17258186/8cf62efa-557a-11e6-9d4c-43caacaaea1f.png)

Thanks.
