### ISSUE TITLE
WSG:  Reports "Download Report Docs Zip" unzips to another zip file…ad infinitum

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#389]
On the submission preview pages for a report, the "Download Report Docs Zip" button yields a .zip file that, when clicked, merely creates another zip file, with a new suffix/extension of ".cpgz".

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=33210&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

<img width="980" alt="screen shot 2016-10-31 at 9 17 49 am" src="https://cloud.githubusercontent.com/assets/17168836/19861840/4dee0e88-9f4b-11e6-9b19-1a012ac9212a.png">

**Comment by ecsion** [comment]
Noted. We will debug and fix.

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
Sorry, but I'm still having the same problem. I'm using OS X 10.11.6, Safari 10.0.1 and Chrome 54.0.2840.71.

**Comment by ecsion** [comment]
will check

**Comment by ecsion** [comment]
fixed (really!).
