### ISSUE TITLE
MASGC- typo in our eSG logo!

### ISSUE THREAD

**Issue by MASGCleist** [ecsion/eSeaGrant-Client-Bug-Tracker#564]
Someone noticed that "Mississippi" is misspelled in our logo.
Please fix.

![logo](https://cloud.githubusercontent.com/assets/22300443/22567868/34c09b0a-e957-11e6-9487-8af6615919fa.JPG)

**Comment by ecsion** [comment]
fixed

**Comment by MASGCleist** [comment]
I gave it a few hours and logged out and in again and the same mistake still appears!

**Comment by MASGCleist** [comment]
It seems to be fixed now!  THANK YOU!
