### ISSUE TITLE
People: User Information "Highest Degree"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#68]
Please remove all "Highest Degree" data from the migrated data for that field (e.g., Emily Roberts has "Ocean Acidification in Mussels"—we don't need anything in here).

**Comment by ecsion** [comment]
done.

**Comment by mgduke** [comment]
Hmmm; we're still having a problem with this in that, while Emily Roberts' record is fine now—as are some others—yet other students still have field of study data in the "Highest Degree" field. I include Emily's URL and several other students for comparison, plus I attach an export of the "Students" MySQL dbase, with some column rearrangement, in hopes this might help you:

http://esg.wsg.washington.edu/index.php?module=People&view=Detail&record=1713
http://esg.wsg.washington.edu/index.php?module=People&view=Detail&record=1586
http://esg.wsg.washington.edu/index.php?module=People&view=Detail&record=1627 

[Students.xlsx](https://github.com/ecsion/eSeaGrant-Bug-Tracker/files/172998/Students.xlsx)

**Comment by ecsion** [comment]
2nd link is still an issue,

**Comment by ecsion** [comment]
fixed for Washington.
