### ISSUE TITLE
CASG: 90-4 Download Issues

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#797]
Hi, 

For some of the[ 2018 Standard Core Award Full Proposals](https://eseagrant2.ucsd.edu/index.php?module=RFP&view=Detail&mode=showProposals&record=40056&phaseid=40057&tab_label=Full-Proposals), the budget worksheets are not converting properly over to the 90-4 form. In particular, the Salaries and Wages (Section A) are not showing up in the 90-4 forms. Two examples are Payton and Kelly.

Please look into this matter.

Thanks,

Miho 
[Paytan_budget90-4_2018.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1240349/Paytan_budget90-4_2018.pdf)
[Paytan_budget_884.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1240350/Paytan_budget_884.pdf)
[Kelly_budget_942.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1240351/Kelly_budget_942.pdf)
[Kelly_budget90-4_2018.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1240352/Kelly_budget90-4_2018.pdf)

**Comment by ecsion** [comment]
fixed, please check.

**Comment by mumezawa** [comment]
The budget justification under "Senior Personnel" is still not showing up for Paytan and Kelly. 
For Steve Morgan's budget, Morgan's budget justification is not showing up. But, Largier and Wolcott's downloaded... 
Thanks. 

Example of Paytan's 2018 budget:
[budget90-4_2018.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1247348/budget90-4_2018.pdf)

Morgan's budget:
[budget90-4_2018.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/1247355/budget90-4_2018.pdf)

**Comment by ecsion** [comment]
fixed.
