### ISSUE TITLE
ORSG- sort and search functionality lost for one column

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#864]
In Reports > Full Reports by Project the first column that will not sort or filter. See below.
Please fix soon. -Thanks
![2018-03-28_1646](https://user-images.githubusercontent.com/17169131/38062293-09e73358-32a8-11e8-9769-ec4b7b1b8286.png)

**Comment by ecsion** [comment]
fixed, please check

**Comment by mcbridec** [comment]
Search is now working on the column, but the Sort function problem is still occurring.

**Comment by ecsion** [comment]
fixed. closing this. Please reopen if you are still having this issue.
