### ISSUE TITLE
WISG - Review Rating not saving

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#903]
We get a "criteria total must be 100%" error when adding criteria review ratings.
Screenshots  below:
<img width="1647" alt="screen shot 2018-11-06 at 10 27 50 am" src="https://user-images.githubusercontent.com/36545478/48079984-3a19d580-e1b2-11e8-9aad-c390695509e4.png">
<img width="476" alt="screen shot 2018-11-06 at 10 27 59 am" src="https://user-images.githubusercontent.com/36545478/48079992-3ede8980-e1b2-11e8-8a6f-858ee0363660.png">

**Comment by ecsion** [comment]
Fixed, please check.

**Comment by tomxiong-aqua** [comment]
Still doesn't work. Please try with more than one criteria to see the error.
Tried on Firefox and Chrome:
<img width="1390" alt="screen shot 2018-11-13 at 9 49 01 am" src="https://user-images.githubusercontent.com/36545478/48424950-6b9e1e00-e729-11e8-86ad-a77a145066c4.png">

**Comment by ecsion** [comment]
Fixed, please check.
